---
- hosts: web
  vars:
    local_dir: build/
    remote_dir: /lumi/web # also need to change in nginx-web.cfg
  tasks:
    - name: Build static react site
      local_action: command yarn run build
    - name: Configure nginx for web frontend
      copy: {src: nginx-web.cfg, dest: /etc/nginx/sites-enabled/web}
      notify: restart nginx
      become: yes
      become_method: sudo
    - name: Deploy static site
      copy: {src: '{{local_dir}}', dest: '{{remote_dir}}'}
      become: yes
      become_user: lumi
  handlers:
    - name: restart nginx
      service: {name: nginx, state: restarted}
      become: yes
      become_method: sudo
