---
# tasks file for wordpress
- name: Download WordPress
  get_url: url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

- name: Upload .env File
  template: { src: env-aws.j2, dest: /var/www/.env, mode: 644 }
  become: yes

- name: Upload wp-config.php
  copy:
    { src: wp-config.php, dest: /var/www/wordpress/wp-config.php, mode: 644 }
  become: yes
# - name: Update WordPress config file
#   lineinfile: dest=/var/www/wordpress/wp-config.php
#     regexp="{{ item.regexp }}"
#     line="{{ item.line }}"
#   with_items:
#     - {
#         "regexp": ".*'DB_HOST'.*",
#         "line": "define('DB_HOST', '{{wp_mysql_host}}');",
#       }
#     - {
#         "regexp": ".*'DB_NAME'.*'",
#         "line": "define('DB_NAME', '{{wp_mysql_db}}');",
#       }
#     - {
#         "regexp": ".*'DB_USER'.*'",
#         "line": "define('DB_USER', '{{wp_mysql_user}}');",
#       }
#     - {
#         "regexp": ".*'DB_PASSWORD'.*'",
#         "line": "define('DB_PASSWORD', '{{wp_mysql_password}}');",
#       }
#   notify: restart apache
#   become: yes
